---
sidebar: sidebar
permalink: upgrade/index.html
keywords:  aggregate, relocation, moving, manual, upgrade, relocate, hardware
summary: Use aggregate relocation to upgrade controller hardware
---

= Use aggregate relocation to upgrade controller hardware
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
This guide describes how to upgrade the controller hardware without disruption by using aggregate relocation.

For other methods of upgrading your controller hardware, see the link:http://docs.netapp.com/platstor/topic/com.netapp.doc.hw-upgrade-controller/home.html[Controller Hardware Upgrade Express Guide].

You can nondisruptively upgrade the controller hardware on a pair of nodes running ONTAP by migrating non-root aggregates from the original nodes to the new nodes in the same cluster. The data hosted on the nodes that are being upgraded is accessible during the upgrade.

This procedure uses a method called aggregate relocation (ARL), which takes advantage of the HA configuration to enable you to move ownership of non-root aggregates from one node to another if they share storage within the same cluster.

There are two ARL methods for upgrading your controller hardware, by using system commands or by performing a manual upgrade. Before you start, you must verify that you have selected the correct guide for your controller hardware upgrade.

If you are performing an upgrade by using system commands refer to the table below:
[cols=2*,options="header",cols="30,70"]
|===
|If you’re running this ONTAP version…
|To upgrade with system commands, use…
|9.8 or later
|link:http://docs.netapp.com/us-en/ontap-systems/upgrade-arl-auto-app/index.html[Using "system controller replace" Commands to Upgrade Controller Hardware Running ONTAP 9.8 or Later]
|9.5 to 9.7
|link:http://docs.netapp.com/us-en/ontap-systems/upgrade-arl-auto/index.html[Using "system controller replace" Commands to Upgrade Controller Hardware Running ONTAP 9.5 to ONTAP 9.7]
|===
If you are performing a manual upgrade refer to the table below:
[cols=2*,options="header",cols="30,70"]
|===
|If you’re running this ONTAP version…
|To manually upgrade, use…
|9.8 or later
|link:http://docs.netapp.com/us-en/ontap-systems/upgrade-arl-manual-app/index.html[Using Aggregate Relocation to Manually Upgrade Controller Hardware Running ONTAP 9.8 or Later]
|9.0 to 9.7
|link:http://docs.netapp.com/us-en/ontap-systems/upgrade-arl-manual/index.html[Using Aggregate Relocation to Manually Upgrade Controller Hardware Running ONTAP 9.7 or Earlier]
|===

// 24 FEB 2021:  formatted from CMS
