---
permalink: upgrade/upgrade-prepare-when-moving-storage.html
sidebar: sidebar
keywords: licenses
summary: 'Before upgrading by moving storage, you must gather license information from the original nodes, plan network configuration, record the system IDs, and prepare the files needed for netboot.'
---
= Prepare for the upgrade when moving storage
:icons: font
:imagesdir: ../media/

[.lead]
Before upgrading by moving storage, you must gather license information from the original nodes, plan network configuration, record the system IDs, and prepare the files needed for netboot.

.Steps
. Display and record license information from the original nodes, node1 and node2:
+
`system license show`
. If you use Storage Encryption on the node1/node2 HA pair and the new nodes have encryption-enabled disks, make sure that the original nodes' disks are correctly keyed:
.. Display information about self-encrypting disks (SEDs)
+
`storage encryption disk show`
.. If any disks are associated with a non-manufacture secure ID (non-MSID) key, rekey them to an MSID key
+
`storage encryption disk modify`
. [[prepare_move_store_3]]Record port and LIF configuration information on the node1/node2 HA pair:
+
[options="header" cols="1,2"]
|===
| To display information about...| Enter...

a|
Shelves, numbers of disks in each shelf, flash storage details, memory, NVRAM, and network cards
a|
`system node run -node <node_name> sysconfig`
a|
Cluster network and node management LIFs
a|
`network interface show -role cluster,node-mgmt`
a|
Physical ports
a|
`network port show -node <node_name> -type physical`
a|
Failover groups
a|
`network interface failover-groups show -vserver <vserver_name>`

Record the names and ports of failover groups that are not clusterwide.
a|
VLAN configuration
a|
`network port vlan show -node <node_name>`

Record each network port and VLAN ID pairing.
a|
Interface group configuration
a|
`network port ifgrp show -node <node_name> -instance`

Record the names of the interface groups and the ports assigned to them.
a|
Broadcast domains
a|
`network port broadcast-domain show`
a|
IPspace information
a|
`network ipspace show`
|===

. Obtain information about the default cluster ports, data ports, and node management ports for each new node that you are upgrading to: https://hwu.netapp.com[NetApp Hardware Universe]
. Download and prepare the files used for performing netboot.
+
After you install the new nodes, you might need to netboot to ensure the new nodes are running the same version of ONTAP as the original nodes. The term netboot means you are booting from an ONTAP image stored on a remote server. When preparing for netboot, you must put a copy of the ONTAP 9 boot image onto a web server that the system can access.

.. Access the https://mysupport.netapp.com/site/[NetApp Support Site] to download the files used for performing the netboot of the system.
.. Download the appropriate ONTAP software from the software download section of the NetApp Support Site and store the `<ontap_version>_image.tgz` file on a web-accessible directory.
.. Change to the web-accessible directory and verify that the files you need are available.

+
[options="header" cols="1,2"]
|===
| For...| Then...

a|
*FAS2200, FAS2500, FAS3200, FAS6200, FAS/AFF8000 series systems*
a|
Extract the contents of the `<ontap_version>_image.tgz` file to the target directory:
`tar -zxvf <ontap_version>_image.tgz`

*Note:* If you are extracting the contents on Windows, use 7-Zip or WinRAR to extract the netboot image.

Your directory listing should contain a netboot folder with a kernel file:
`netboot/kernel`

a|
*All other systems*
a|
Your directory listing should contain the following file:

`<ontap_version>_image.tgz`

NOTE: You do not need to extract the contents of the `<ontap_version>_image.tgz` file.

|===

You will use information in the directory to link:setting_up_the_new_nodes.html#[Set up the new nodes].
