---
permalink: upgrade/upgrade_considerations_move_san_lifs.html
sidebar: sidebar
keywords: cluster, san, environment, lif, original, node, unjoin, original, move san lifs
summary: You only need move SAN LIFs if you are changing the contents of your cluster.
---
= Considerations for moving SAN LIFs
:icons: font
:imagesdir: ../media/

[.lead]
You only need to move the SAN LIFs if you are changing the contents of your cluster, for example, by adding nodes to the cluster or deleting nodes from the cluster. When you move a LIF, you do not have to re-zone your FC fabric or create new iSCSI sessions between the attached hosts of your cluster and the new target interface.

You can move a SAN LIF by using the `network interface modify` command. To move a SAN LIF, you must take the LIF offline, move the LIF to a different home node or port, and then bring it back online in its new location. Asymmetric Logical Unit Access (ALUA) provides redundant paths and automatic path selection as part of any ONTAP SAN solution. Therefore, when the LIF is taken offline for the movement, there is no I/O interruption. The host simply retries and then moves I/O to another LIF.

During the LIF movements, you can nondisruptively perform the following tasks:

* Replace one HA pair of a cluster with an upgraded HA pair in a way that is transparent to the hosts accessing LUN data
* Upgrade a target interface card
* Shift the resources of a storage virtual machine (SVM) from one set of nodes in a cluster to another set of nodes in the same cluster
* When the host server is online, you can move a SAN LUN to a new HA pair without disrupting the host server access to the LUN data

For more information, see the https://docs.netapp.com/us-en/ontap/san-admin/move-san-lifs-task.html[SAN LIF movement^] procedure in the _SAN storage management_ documentation.
