---
permalink: upgrade/upgrade-optional-move-internal-storage.html
sidebar: sidebar
keywords: node, support, model, internal, sata, drive, ssd, moving, move, upgrading, upgrade, convert, move internal storage or convert the system to a drive shelf
summary: If your original node is one of the supported models, you can move its internal SATA drives or SSDs to a drive shelf that is attached to the new nodes during the process of upgrading by moving storage. You can also convert the system to a drive shelf and attach it to the new nodes.
---
= Optional: Move internal storage or convert the system to a drive shelf
:icons: font
:imagesdir: ../media/

[.lead]
If your original node is one of the supported models, you can move its internal SATA drives or SSDs to a drive shelf that is attached to the new nodes during the process of upgrading by moving storage. You can also convert the system to a drive shelf and attach it to the new nodes.

.About this task
You can move drives or drive shelves only within the same cluster.

.Choices
* link:upgrade-move-internal-drives.html[Move internal drives from an original node]
+
If your original node is one of the supported models, during the process of upgrading by moving
storage you can move the node's internal SATA drives or SSDs to a drive shelf that is attached to
the new node in the same cluster. You cannot transfer SAS drives to a drive shelf attached to the
new nodes.

* link:upgrade-convert-node-to-shelf.html[Convert an original node to a drive shelf]
+
If your original node is one of the supported models, during the process of upgrading by moving
storage you can convert the node to a drive shelf and then attach it to the new nodes in the same
cluster..
