---
permalink: upgrade/upgrade-map-network-ports-ontap-9-7-or-earlier.html
sidebar: sidebar
keywords: enable, node3, node4, node, communicate, cluster, network, upgrade, physical, port, configure, setting, intend, data, map, map network ports using ontap 9.7 or earlier
summary: To enable node3 and node4 to communicate with each other in the cluster and with the network after the upgrade, you need to ensure the physical ports are correctly configured with the settings for the intended use, such as cluster, data, and so on.
---
= Map network ports using ONTAP 9.7 or earlier
:icons: font
:imagesdir: ../media/

[.lead]
To enable node3 and node4 to communicate with each other in the cluster and with the network after the upgrade, you need to ensure the physical ports are correctly configured with the settings for the intended use, such as cluster, data, and so on.

.Before you begin
These steps apply to systems running ONTAP 9.7 or earlier. If you are running ONTAP 9.8, you must use the procedure in xref:upgrade-map-network-ports-ontap-9-8.adoc[Map network ports using ONTAP 9.8].

.About this task
You need to perform these steps on node3 and node4.

NOTE: The following command examples refer to "node1" because at this stage in the procedure the replacement nodes "node3" and "node4" are actually named "node1" and "node2".

.Steps
. If your system is running ONTAP 9.8, *STOP*. You must use the procedure in xref:upgrade-map-network-ports-ontap-9-8.adoc[Map network ports using ONTAP 9.8].
. Locate the port and LIF configuration information for node1 and node2 that you recorded in _Prepare for upgrade when moving storage_, link:upgrade-prepare-when-moving-storage.html#prepare_move_store_3[Step 3].
. Locate the information for ports, broadcast domains, and IPspaces that you recorded in  _Prepare for upgrade when moving storage_, link:upgrade-prepare-when-moving-storage.html#prepare_move_store_3[Step 3].
+
https://hwu.netapp.com[NetApp Hardware Universe^]

. Make the following changes:
.. Boot node3 and node4 to the cluster prompt if you have not already done so.
.. Add the correct ports to the `Cluster` broadcast domain:
+
`network port modify -node <node_name> -port <port_name> -mtu 9000 -ipspace Cluster`
+
This example adds `Cluster` port e1b on "`node1`":
+
`network port modify -node node1 -port e1b -ipspace Cluster -mtu 9000`

.. Migrate the LIFs to the new ports, once for each LIF:
+
`network interface migrate -vserver <vserver_name> -lif <lif_name> -source-node node1 -destination-node node1 -destination-port <port_name>`
+
SAN data LIFs can be migrated only when they are offline.

.. Modify the home port of the Cluster LIFs:
+
`network interface modify -vserver Cluster -lif <lif_name> –home-port <port_name>`
.. Remove the old ports from the Cluster broadcast domain:
+
`network port broadcast-domain remove-ports -ipspace Cluster -broadcast-domain Cluster -ports <node1:port>`
.. Display the health state of node3 and node4:
+
`cluster show -node <node1> -fields health`
. Modify the VLAN and `ifgrp config` to match the new controller physical port layout.
. Delete the node1 and node2 ports that no longer exist on node3 and node4 (advanced privilege level):
+
`network port delete -node <node1> -port <port_name>`
. [[map_97_7]] Adjust the node-management broadcast domain and migrate the node-management and cluster-management LIFs if necessary:
.. Display the home port of a LIF:
+
`network interface show -fields home-node,home-port`
.. Display the broadcast domain containing the port:
+
`network port broadcast-domain show -ports <node_name:port_name>`
.. Add or remove ports from broadcast domains as necessary:
+
`network port broadcast-domain add-ports`
+
`network port broadcast-domain remove-ports`
.. Modify a LIF's home port if necessary:
+
`network interface modify -vserver <vserver_name> -lif <lif_name> –home-port <port_name>`
. Adjust the intercluster broadcast domains and migrate the intercluster LIFs, if necessary, using the commands in <<map_97_7,Step 7>>.
. Adjust any other broadcast domains and migrate the data LIFs, if necessary, using the commands in <<map_97_7,Step 7>>.
. Adjust all the LIF failover groups:
+
`network interface modify -failover-group <failover_group> -failover-policy <failover_policy>`
+
The following command sets the failover policy to broadcast-domain-wide and uses the ports in failover group "fg1" as failover targets for LIF "data1" on "node1":
+
`network interface modify -vserver node1 -lif data1 -failover-policy broadcast-domain-wide -failover-group fg1`

. Display node3 and node4 's network port attributes:
+
`network port show -node node1`

.After you finish
You have completed mapping the physical ports. To complete the upgrade, go to xref:upgrade-final-steps-ontap-9-7-or-earlier-move-storage.adoc[Perform final upgrade steps in ONTAP 9.7 or earlier].
