---
sidebar: sidebar
permalink: upgrade-arl-auto/recreate_vlans_ifgrps_broadcast_domains_node4.html
keywords: node4, interface group, VLANs, broadcast domains, re-create
summary: After you confirm that node4 is in quorum and can communicate with node3, you must re-create node2's VLANs, interface groups, and broadcast domains on node4.
---

= Re-create VLANs, interface groups, and broadcast domains on node4
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

// similar to section for node2
// last section of pg. 64 and beginning of 65 in PDF.
After you confirm that node4 is in quorum and can communicate with node3, you must re-create node2's VLANs, interface groups, and broadcast domains on node4. You must also add the node3 ports to the newly re-created broadcast domains.

.About this task

For more information on creating and re-creating VLANs, interface groups, and broadcast domains, go to link:other_references.html[References] and link to the _ONTAP 9 Network Management Guide_.

.Steps

. Re-create the VLANs on node4 using the node2 information recorded in the link:relocate_non_root_aggr_nas_lifs_from_node2_to_node3.html[Relocate non-root aggregates and NAS data LIFs from node2 to node3] section:
+
`network port vlan create -node <node4> -vlan <vlan-names>`

. Re-create the interface groups on node4 using the node2 information recorded in the link:relocate_non_root_aggr_nas_lifs_from_node2_to_node3.html[Relocate non-root aggregates and NAS data LIFs from node2 to node3] section:
+
`network port ifgrp create -node <node4> -ifgrp <port_ifgrp_names>-distr-func`

. Re-create the broadcast domains on node4 using the node2 information recorded in the link:relocate_non_root_aggr_nas_lifs_from_node2_to_node3.html[Relocate non-root aggregates and NAS data LIFs from node2 to node3] section:
+
`network port broadcast-domain create -ipspace Default -broadcast-domain <broadcast_domain_names> -mtu <mtu_size> -ports <node_name:port_name,node_name:port_name>`

. Add the node4 ports to the newly re-created broadcast domains:
+
`network port broadcast-domain add-ports -broadcast-domain <broadcast_domain_names> -ports <node_name:port_name,node_name:port_name>`
