---
sidebar: sidebar
permalink: upgrade-arl-auto/recreate_vlans_ifgrps_broadcast_domains_node3.html
keywords: node3, interface group, VLANs, broadcast domains, re-create
summary: After you confirm that node3 is in quorum and can communicate with node2, you must re-create node1's VLANs, interface groups, and broadcast domains on node3.
---

= Re-create VLANs, interface groups, and broadcast domains on node3
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
After you confirm that node3 is in quorum and can communicate with node2, you must re-create node1's VLANs, interface groups, and broadcast domains on node3. You must also add the node3 ports to the newly re-created broadcast domains.

.About this task

For more information on creating and re-creating VLANs, interface groups, and broadcast domains, go to link:other_references.html[References] and link to _Network Management_.

.Steps

. Re-create the VLANs on node3 using the node1 information recorded in the link:relocate_non_root_aggr_and_nas_data_lifs_node1_node2.html[Relocate non-root aggregates and NAS data LIFs owned by node1 to node2] section:
+
`network port vlan create -node <node_name> -vlan <vlan-names>`

. Re-create the interface groups on node3 using the node1 information recorded in the link:relocate_non_root_aggr_and_nas_data_lifs_node1_node2.html[Relocate non-root aggregates and NAS data LIFs owned by node1 to node2] section:
+
`network port ifgrp create -node <node_name> -ifgrp <port_ifgrp_names>-distr-func`

. Re-create the broadcast domains on node3 using the node1 information recorded in the link:relocate_non_root_aggr_and_nas_data_lifs_node1_node2.html[Relocate non-root aggregates and NAS data LIFs owned by node1 to node2] section:
+
`network port broadcast-domain create -ipspace Default -broadcast-domain <broadcast_domain_names> -mtu <mtu_size> -ports <node_name:port_name,node_name:port_name>`

. Add the node3 ports to the newly re-created broadcast domains:
+
`network port broadcast-domain add-ports -broadcast-domain <broadcast_domain_names> -ports <node_name:port_name,node_name:port_name>`
