---
sidebar: sidebar
permalink: upgrade-arl-auto/relocate_failed_or_vetoed_aggr.html
keywords: relocate, aggregates, fail, veto
summary: If any aggregates fail to relocate or are vetoed, you must take manually relocate the aggregates.
---

= Relocate failed or vetoed aggregates
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
If any aggregates fail to relocate or are vetoed, you must take manually relocate the aggregates, or override either the vetoes or destination checks, if necessary.

.About this task

The relocation operation will have paused due to the error.

.Steps

. Check the EMS logs to determine why the aggregate failed to relocate or was vetoed.

. Relocate any failed or vetoed aggregates:
+
`storage aggregate relocation start -node <node1> -destination <node2> aggregate-list * -ndocontroller-upgrade true`

. When prompted, enter `y`.

. You can force relocation by using one of the following methods:
+
[cols="35,65"]
|===
|Option |Description

|Overriding veto checks
|Enter the following:

`storage aggregate relocation start -override-vetoes * -ndocontroller-upgrade true`
|Overriding destination checks
|Enter the following:

`storage aggregate relocation start -overridedestination-checks * -ndo-controllerupgrade true`
|===
