---
sidebar: sidebar
permalink: upgrade-arl-auto/stage_5_install_and_boot_node4.html
keywords: install, boot, node4, node2, node-management
summary: During Stage 5, you install and boot node4, map the cluster and node-management ports from node2 to node4.
---

= Stage 5. Install and boot node4
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

During Stage 5, you install and boot node4, map the cluster and node-management ports from node2 to node4, and verify the node4 installation. You also move the NAS data LIFs owned by node2 from node3 to node4, and relocate node2's aggregates from node3 to node4.

.Steps

. link:install_boot_node4.html[Install and boot node4]
. link:set_fc_or_uta_uta2_config_node4.html[Set the FC or UTA/UTA2 configuration on node4]
. link:map_ports_node2_node4.html[Map ports from node2 to node4]
. link:join_quorum_node_has_different_ports_stage5.html[Join the quorum when a node has a different set of network ports]
. link:verify_node4_installation.html[Verify the node4 installation]
. link:restore_key-manager_config_node4.html[Restore key-manager configuration on node4]
. link:move_non_root_aggr_and_nas_data_lifs_node2_from_node3_to_node4.html[Move non-root aggregates and NAS data LIFs owned by node2 from node3 to node4]
