---
sidebar: sidebar
permalink: upgrade-arl-auto/verify_node3_installation.html
keywords: install, boot, node3, join quorum
summary: After you install and boot node3, you need to verify that it is installed correctly.
---

= Verify the node3 installation
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
After you install and boot node3, you need to verify that it is installed correctly. You must wait for node3 to join quorum and then resume the relocation operation.

.About this task

At this point in the procedure, the operation will have paused as node3 joins quorum.

.Steps

. Verify that node3 has joined quorum:
+
`cluster show -node node3 -fields health`

. Verify that node3 is part of the same cluster as node2 and that it is healthy:
+
`cluster show`

. Check the status of the operation and verify that the configuration information for node3 is the same as node1:
+
`system controller replace show-details`
+
If the configuration is different for node3, a system disruption might occur later in the procedure.

. Check that the replaced controller is configured correctly for the MetroCluster configuration, the MetroCluster configuration should be in healthy state and not in switch over mode. Refer to link:verify_health_of_metrocluster_config.html[Verify the health of the MetroCluster configuration].

== Re-create VLANs, interface groups, and broadcast domains on node3

After you confirm that node3 is in quorum and can communicate with node2, you must re-create node1's VLANs, interface groups, and broadcast domains on node3. You must also add the node3 ports to the newly re-created broadcast domains.

.About this task

For more information on creating and re-creating VLANs, interface groups, and broadcast domains, go to link:other_references.html[References] and link to _Network Management_.

.Steps

. Re-create the VLANs on node3 using the node1 information recorded in the link:relocate_non_root_aggr_and_nas_data_lifs_node1_node2.html[Relocate non-root aggregates and NAS data LIFs owned by node1 to node2] section:
+
`network port vlan create -node <node_name> -vlan <vlan-names>`

. Re-create the interface groups on node3 using the node1 information recorded in the link:relocate_non_root_aggr_and_nas_data_lifs_node1_node2.html[Relocate non-root aggregates and NAS data LIFs owned by node1 to node2] section:
+
`network port ifgrp create -node <node_name> -ifgrp <port_ifgrp_names>-distr-func`

. Re-create the broadcast domains on node3 using the node1 information recorded in the link:relocate_non_root_aggr_and_nas_data_lifs_node1_node2.html[Relocate non-root aggregates and NAS data LIFs owned by node1 to node2] section:
+
`network port broadcast-domain create -ipspace Default -broadcast-domain <broadcast_domain_names> -mtu <mtu_size> -ports <node_name:port_name,node_name:port_name>`

. Add the node3 ports to the newly re-created broadcast domains:
+
`network port broadcast-domain add-ports -broadcast-domain <broadcast_domain_names> -ports <node_name:port_name,node_name:port_name>`

== Restore key-manager configuration on node3

If you are using NetApp Volume Encryption (NVE) to encrypt volumes on the system you are upgrading, the encryption configuration must be synchronized to the new nodes. Encrypted volumes are taken offline when ARL is complete for node1 aggregates from node2 to node3.

include::../_include/ru_auto_restore_key_manager_config_ontap_95_97.adoc[]

// bottom half of p. 42. in PDF
