---
sidebar: sidebar
permalink: upgrade-arl-auto-mendocino/guidelines_for_upgrading_controllers_with_arl.html
keywords: guidelines, upgrade, aff, a900, a700, ontap, controllers
summary: Using ARL to upgrade a pair of AFF A700 controllers running ONTAP 9.10.1 or later to an AFF A900 system depends on the system and the controller configuration.
---

= Guidelines for upgrading from an AFF A700 to an AFF A900 with ARL
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Using ARL to upgrade a pair of AFF A700 controllers running ONTAP 9.10.1 or later to an AFF A900 system depends on the system and the configuration of both the original and replacement controllers.

== Supported upgrades for ARL
An AFF A700 to an AFF A900 upgrade using ARL and swapping only the controller module and the NVS is the supported combination. If you have received a new AFF A900 system as a complete system, including a new chassis, refer to link:other_references.html[References] to link to the _Use "system controller replace" commands to upgrade controller hardware running ONTAP 9.8 or later_ content.

WARNING: This guide strictly applies to an AFF A700 to an AFF A900 upgrade running ONTAP 9.10.1 or later. Do not use this guide to perform an upgrade between any other system combinations.

Controller upgrade using ARL is supported on systems configured with SnapLock Enterprise and SnapLock Compliance volumes.

== Two-node switchless clusters

If you are upgrading nodes in a two-node switchless cluster, you can leave the nodes in the switchless cluster while performing the upgrade. You do not need to convert them to a switched cluster.

== Troubleshoot

If any problems occur while upgrading the controllers, you can refer to the link:troubleshoot_index.html[Troubleshoot] section at the end of the procedure for more information and possible solutions.

If you do not find a solution to the problem you encountered, you should contact technical support.
