Before starting an upgrade on a Fabric MetroCluster configuration, you must check the health of the MetroCluster configuration to verify proper operation.

.Steps

. Verify that the MetroCluster components are healthy by using the following command:
+
`metrocluster check run`
+
....
metrocluster_siteA::*> metrocluster check run
....
+
The operation runs in the background.

. After the `metrocluster check run` operation completes, view the results by using the following command:
+
`metrocluster check show`
+
After approximately five minutes, the following results are displayed:
+
----
metrocluster_siteA::*> metrocluster check show
Last Checked On: 4/7/2019 21:15:05
Component            Result
---------------      -------
nodes                ok
lifs                 ok
config-replication   ok
aggregates           warning
clusters             ok
connections          not-applicable
volumes              ok
7 entries were displayed.
----

. Check the status of the running MetroCluster check operation by using the following command:
+
`metrocluster operation history show -job-id 38`

. Verify that there are no health alerts by using the following command:
+
`system health alert show`