---
sidebar: sidebar
permalink: upgrade-arl-auto-app/automate_the_controller_upgrade_process.html
keywords: automating, controller, upgrade, process, network, port, ha
summary: During a controller upgrade, the controller is replaced with another controller.
---

= Automating the controller upgrade process
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-12-02 14:33:53.664517
//

[.lead]
During a controller upgrade, the controller is replaced with another controller running a newer or more powerful platform. Earlier versions of this guide contained instructions for a nondisruptive controller update process that was comprised of entirely manual steps. This guide provides the steps for the new automated procedure which utilizes automatic network port reachability checks to further simplify the controller upgrade experience.

The manual process was lengthy and complex but in this simplified procedure you can implement a controller update using aggregate relocation, allowing for more efficient nondisruptive upgrades for HA pairs. There are significantly fewer manual steps, especially around validation, collection of information, and post checks.
