---
sidebar: sidebar
permalink: upgrade-arl-auto-app/move_non_root_aggr_and_nas_data_lifs_node2_from_node3_to_node4.html
keywords: move, non-root, aggregates, nas, lif, node2, node3, node4
summary: After you verify network configuration on node4 and before you relocate aggregates from node3 to node4.
---

= Move non-root aggregates and NAS data LIFs owned by node2 from node3 to node4
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-12-02 14:33:55.666158
//

[.lead]
After you verify network configuration on node4 and before you relocate aggregates from node3 to node4, you must verify that the NAS data LIFs belonging to node2 that are currently on node3 are relocated from node3 to node4. You must also verify that the SAN LIFs exist on node4.

.About this task

Remote LIFs handle traffic to SAN LUNs during the upgrade procedure. Moving SAN LIFs is not necessary for cluster or service health during the upgrade. SAN LIFs are not moved unless they need to be mapped to new ports. You will verify that the LIFs are healthy and located on appropriate ports after you bring node4 online.

.Steps

. Resume the relocation operation by using the following command:
+
`system controller replace resume`
+
The system performs the following tasks:

* Cluster quorum check
* System ID check
* Image version check
* Target platform check
* Network reachability check

+
The operation pauses at this stage in the network reachability check.
[start=2]
. Resume the relocation operation by using the following command:
+
`system controller replace resume`

. The system performs the following checks:
+
* Cluster health check
* Cluster LIF status check

+
After performing these checks, the system relocates the non-root aggregates and NAS data LIFs owned by node2 to the new controller, node4.
The controller replacement operation  pauses after the resource relocation is complete.
[start=4]
. Check the status of the aggregate relocation and NAS data LIF move operations by using the following command:
+
`system controller replace show-details`
+
If the controller replacement procedure is paused, check and correct the error,  if any,  and then issue `resume` to continue the operation.

. If necessary, restore and revert any displaced LIFs. List any displaced LIFs by using the following command:
+
`cluster controller-replacement network displaced-interface show`
+
If any LIFs are displaced, restore the home node back to node4 by using the following command:
+
`cluster controller-replacement network displaced-interface restore-home-node`

. Resume the operation to prompt the system to perform the required post-checks by using the following command:
+
`system controller replace resume`
+
The system performs the following post-checks:
+
* Cluster quorum check
* Cluster health check
* Aggregates reconstruction check
* Aggregate status check
* Disk status check
* Cluster LIF status check
* Volume check
// 11 DEC 2020, thomi, checked
