---
sidebar: sidebar
permalink: upgrade-arl-manual-app/guidelines_upgrade_with_arl.html
keywords: guidelines, upgrade
summary: Guidelines for upgrade controllers with ARL
---

= Guidelines for upgrading controllers with ARL
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
To understand whether you can use aggregate relocation (ARL) to upgrade a pair of controllers running ONTAP 9.8 depends on the platform and the configuration of both the original and replacement controllers.

== Supported upgrades for ARL
You can upgrade a pair of nodes using ARL under the following circumstances:


* Both the original controllers and the replacement controllers must be running the same version of ONTAP 9.8 before the upgrade.

include::../_include/ru_man_supported_upgrades_chunk_a.adoc[]
include::../_include/ru_man_supported_upgrades_chunk_b.adoc[]

== Upgrades not supported for ARL

You cannot perform the following upgrades:

* To or from controllers that cannot run ONTAP 9.8 or later.

* To replacement controllers that do not support the disk shelves connected to the original controllers.
+
For disk-support information, refer to link:other_references.html[References] to link to the _Hardware Universe_.

* From controllers with root aggregates or data aggregates on internal drives.
+
If you want to upgrade controllers with root aggregates or data aggregates on internal disk drives, refer to link:other_references.html[References] to link to _Upgrade by moving volumes or storage_ and go to the procedure _Upgrading a pair of nodes running clustered Data ONTAP by moving volumes_.
+
NOTE: If you want to upgrade ONTAP on nodes in a cluster, refer to link:other_references.html[References] to link to _Upgrade ONTAP_.

== Assumptions and terminology

include::../_include/ru_man_assumptions_terminology.adoc[]

== Licensing in ONTAP 9.8 or Later

include::../_include/ru_man_licensing.adoc[]

All license keys are 28 uppercase alphabetic characters in length. Refer to link:other_references.html[References] to link to the _NetApp Support Site_ where you can obtain new 28-character license keys for ONTAP 9.8. or later. The keys are available in the _My Support_ section under _Software licenses_. If the site does not have the license keys you need, contact your NetApp sales representative.

For detailed information about licensing, go to link:other_references.html[References] to link to the _System Administration Reference_.

== Storage Encryption

include::../_include/ru_man_storage_encryption.adoc[]

== Two-node switchless clusters

If you are upgrading nodes in a two-node switchless cluster, you can leave the nodes in the switchless cluster while performing the upgrade. You do not need to convert them to a switched cluster

== Troubleshooting

include::../_include/ru_man_troubleshooting.adoc[]
