---
sidebar: sidebar
permalink: upgrade-arl-manual-app/map_ports_node1_node3.html
keywords: map, ports, node1, node3, cluster, home port, vlan ports, broadcast domain, connectivity
summary: Map ports from node1 to node3
---

= Map ports from node1 to node3
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
include::../_include/ru_man_map_ports_node1_node3_intro.adoc[]

.Steps

. [[step1]]Perform the following steps to verify if the setup is a two-node switchless cluster:

.. Set the privilege level to advanced:
+
`set -privilege advanced`

.. Verify if the setup is a two-node switchless cluster:
+
`network options switchless-cluster show`
+
For example:
+
----
 cluster::*> network options switchless-cluster show
 Enable Switchless Cluster: false/true
----
+
The value of this command must match the physical state of the system.

.. Return to the administration privilege level:
+
`set -privilege admin`

. [[step2]]Make the following changes:

.. Modify ports that will be part of Cluster broadcast domain:
+
`network port modify -node <node_name> -port <port_name> -mtu 9000 -ipspace Cluster`
+
This example adds Cluster port e1b on "node1":
+
----
network port modify -node node1 -port e1b -ipspace Cluster -mtu 9000
----

.. Migrate the cluster LIFs to the new ports, once for each LIF:
+
`network interface migrate -vserver <Vserver_name> -lif <lif_name> -source-node <node1> -destination-node <node1> -destination-port <port_name>`
+
When all cluster LIFs are migrated and cluster communication is established, the cluster should come into quorum.

.. Modify the home port of the Cluster LIFs:
+
`network interface modify -vserver Cluster -lif <lif_name> –home-port <port_name>`

.. Remove the old ports from the Cluster broadcast domain:
+
`network port broadcast-domain remove-ports -ipspace Cluster -broadcast-domain Cluster -ports <node1:port>`

.. Display the health state of node1 and node3:
+
`cluster show -node <node1> -fields health`

. [[man_map_1_step3]]Modify the broadcast domain memberships of physical ports hosting data LIFs.

.. List the reachability status of all ports:
+
`network port reachability show`

.. Repair the reachability of the physical ports, followed by VLAN ports, by running the following command on each port, one port at a time:
+
`reachability repair -node <node_name> -port <port_name>`
+
A warning like the following is expected. Review and enter `y` or `n` as appropriate:
+
----
WARNING: Repairing port "node_name:port" might cause it to move into a different broadcast domain, which can cause LIFs to be re-homed away from the port. Are you sure you want to continue? {y|n}:
----

.. To allow ONTAP to complete the repair, wait for about a minute after running the `reachability repair` command on the last port.

.. List all broadcast domains on the cluster:
+
`broadcast-domain show`

.. As the reachability repair is performed, ONTAP attempts to place the ports in the correct broadcast domains. However, if a port’s reachability cannot be determined and does not correspond to any of the existing broadcast domains, ONTAP will create new broadcast domains for these ports. As required, you can delete the newly created broadcast domains if all their member ports will become member ports of the interface groups. Delete broadcast domains:
+
`broadcast-domain delete -broadcast-domain <broadcast_domain>`

.. Review the interface group configuration, and as required, add or delete member ports.
+
Add member ports to interface group ports:
+
`ifgrp add-port -node <node_name> -ifgrp <ifgrp_port> -port <port_name>`
+
Remove member ports from interface group ports:
+
`ifgrp remove-port -node _<node_name>_ -ifgrp <ifgrp_port> -port <port_name>`

.. Delete and re-create VLAN ports as needed. Delete VLAN ports:
+
`vlan delete -node <node_name> -vlan-name <vlan_port>_`
+
Create VLAN ports:
+
`vlan create -node <node_name> -vlan-name<vlan_port>`
+
NOTE: Depending on the complexity of the networking configuration of the system being upgraded, you might be required to repeat Substeps (a) to (g) until all ports are placed correctly where needed.


. [[step4]]If there are no VLANs configured on the system, go to <<man_map_1_step5,Step 5>>. If there are VLANs configured, restore displaced VLANs that were previously configured on ports that no longer exist or were configured on ports that were moved to another broadcast domain.

.. Display the displaced VLANs:
+
`displaced-vlans show`

.. Restore the displaced VLANs to the desired destination port:
+
`displaced-vlans restore -node <node_name> -port <port_name> -destination-port <destination_port>`

.. Verify that all displaced VLANs have been restored:
+
`displaced-vlans show`

.. VLANs are automatically placed into the appropriate broadcast domains about a minute after they are created. Verify that the restored VLANs have been placed into the appropriate broadcast domains:
+
`network port reachability show`

. [[man_map_1_step5]]Starting with ONTAP 9.8, ONTAP will automatically modify the home ports of LIFs if the ports are moved between broadcast domains during the network port reachability repair procedure. If a LIF’s home port was moved to another node, or is unassigned, that LIF will be presented as a displaced LIF. Restore the home ports of displaced LIFs whose home ports either no longer exist or were relocated to another node.

.. Display the LIFs whose home ports might have moved to another node or no longer exist:
+
`displaced-interface show`

.. Restore the home port of each LIF:
+
`displaced-interface restore -vserver <Vserver_name> -lif-name <LIF_name>`

.. Verify that all LIF home ports have been restored:
+
`displaced-interface show`

+
When all ports are correctly configured and added to the correct broadcast domains, the `network port reachability show` command should report the reachability status as "ok" for all connected ports, and the status as "no-reachability" for ports with no physical connectivity. If any ports are reporting a status other than these two, repair the reachability as outlined in <<man_map_1_step3,Step 3>>.

. [[man_map_1_step6]]Verify that all LIFs are administratively up on ports belonging to the correct broadcast domains.

.. Check for any LIFs that are administratively down:
+
`network interface show -vserver <Vserver_name> -status-admin down`

.. Check for any LIFs that are operationally down:
+
`network interface show -vserver <Vserver_name> -status-oper down`

.. Modify any LIFs that need to be modified to have a different home port:
+
`network interface modify -vserver <Vserver_name> -lif <LIF_name> -home-port <home_port>`
+
NOTE: For iSCSI LIFs, modification of the home port requires the LIF to be administratively down.

.. Revert LIFs that are not home to their respective home ports:
+
`network interface revert *`
// 24 FEB 2021: formatted from CMS
