---
sidebar: sidebar
permalink: upgrade-arl/index.html
keywords:  aggregate, relocation, moving, manual, upgrade, relocate, hardware
summary: Use aggregate relocation to upgrade controller hardware
---

= Use aggregate relocation to upgrade controller hardware
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
This content describes how to upgrade the controller hardware without disruption by using aggregate relocation (ARL).

For other methods of upgrading your controller hardware, refer to link:other_references.html[References] to link to _Upgrade by moving volumes or storage_.

You can nondisruptively upgrade the controller hardware on a pair of nodes running ONTAP by migrating non-root aggregates from the original nodes to the new nodes in the same cluster. The data hosted on the nodes that are being upgraded is accessible during the upgrade.

ARL takes advantage of the HA configuration to give you the capability you to move ownership of non-root aggregates from one node to another if they share storage within the same cluster.

There are two ARL methods for upgrading your controller hardware, using system commands or performing a manual upgrade. Before you start, you must verify that you have selected the correct guide for your controller hardware upgrade.

If you are performing an upgrade by using system commands refer to the following table:
[cols=2*,options="header",cols="30,70"]
|===
|If you’re running this ONTAP version…
|To upgrade with system commands, use…
|9.8 or later
|link:upgrade-arl-auto-app/index.html[Using "system controller replace" Commands to Upgrade Controller Hardware Running ONTAP 9.8 or Later]
|9.5 to 9.7
|link:upgrade-arl-auto/index.html[Using "system controller replace" Commands to Upgrade Controller Hardware Running ONTAP 9.5 to ONTAP 9.7]
|===
If you are performing a manual upgrade refer to the following table:
[cols=2*,options="header",cols="30,70"]
|===
|If you’re running this ONTAP version…
|To manually upgrade, use…
|9.8 or later
|link:upgrade-arl-manual-app/index.html[Using Aggregate Relocation to Manually Upgrade Controller Hardware Running ONTAP 9.8 or Later]
|9.0 to 9.7
|link:upgrade-arl-manual/index.html[Using Aggregate Relocation to Manually Upgrade Controller Hardware Running ONTAP 9.7 or Earlier]
|===

// 24 FEB 2021:  formatted from CMS
